| Backlog ID | Tipo do item | Descrição                         | Prioridade | Especifidades                                                                                                                                                                                         | Pontuação | Status   | Sprint designada | Critérios | Tecnologias utilizadas |
|------------|--------------|-----------------------------------|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|----------|------------------|-----------|------------------------|
| RNF01      | DESIGN       | SELEÇÃO DE COR BASE DO SITE       |            | Identidade visual com referencias de cor e designer                                                                                                                                                   | 1         | Relizado | Sprint 1         | DD-001    | ADOBE COLOR, FIGMA     |
| RNF01      | DESIGN       | CRIAÇÃO PAGINA BASE               |            | Criar página base com header e footer que serão utilizados como padrão para todas as páginas seguintes                                                                                                | 3         | Relizado | Sprint 1         | DD-002    | FIGMA                  |
| RNF01      | FRONTEND     | CRIAÇÃO PAGINA BASE               |            | Criar uma página base com o header e footer que servirá de padrão para todas as páginas seguintes                                                                                                     | 5         | 30.00%   | Sprint 1         |           |                        |
| RF01       | DESIGN       | CRIAÇÂO DE UMA PAGINA HOME        |            | Criar uma página home OBRIGATÓRIAMENTE contendo cards de notícias, projeto, publicações ou outras atualizações, colaboradores, descrições sobre o INPE e o laboratório e previews das demais páginas. | 5         | 70.00%   | Sprint 1         | DD-003    | FIGMA                  |
| RF03       | DESIGN       | CRIAÇÃO DE UMA PÁGINA DE MEMBROS  |            | Criar uma página referente aos membros do laboratório, descrevendo tambem as respectivas àreas de atuação, nome, foto, função e breve descrição.                                                      | 5         | 70.00%   | Sprint 1         | DD-004    | FIGMA                  |
| RF02       | DESIGN       | CRIAÇÃO DE UMA PÁGINA "SOBRE"     |            | Criar uma página descrevendo com detalhes o laboratório, contendo OBRIGATÓRIAMENTE objetivo, foco, descrição sobre as àreas de atuação e textos explicativos                                          | 3         | 90.00%   | Sprint 1         | DD-005    | FIGMA                  |
| RF04       | DESIGN       | CRIAÇÃO DE UMA PÁGINA DE VAGAS    |            | Criar uma página de vagas contendo instruções sobre como se candidatar, oportunidades e parcerias estabelecidas pelo laboratório                                                                      | 3         | 90.00%   | Sprint 1         | DD-006    | FIGMA                  |
| RF05       | DESIGN       | CRIAÇÃO DE UMA PÁGINA DE PROJETOS |            | Criar uma página de projetos contendo OBRIGATÓRIAMENTE título, resumo, ano de início, status e equipe envolvida.                                                                                      | 5         | 50.00%   | Sprint 1         | DD-007    | FIGMA                  |
| RF06       | DESIGN       | CRIAÇÃO DE UMA PÁGINA DE NOTÍCIAS |            | Criar uma página de notícias permitindo OBRIGATÓRIAMENTE a publicação de notícias contendo título, data, imagem e texto. As notícias devem ser organizadas cronológicamente                           | 5         | 90.00%   | Sprint 1         | DD-008    | FIGMA                  |
